### ISSUE TITLE
environment and codeRepo fields are missing

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#133]
Related to https://github.com/topcoder-platform/community-app/issues/4428

[V4 Call](https://api.topcoder-dev.com/v4/challenges/30051802) bring these details which **direct** fields 

```
environment: "assada",
codeRepo: "dasda",
```

These files are missing on v5 

http://api.topcoder-dev.com/v5/challenges/a917675b-950f-4f62-aa72-d543f49798e1

**Comment by rootelement** [comment]
This is fixed in dev, will be migrated in prod soon.

You can see them here, in the metadata object:
http://api.topcoder-dev.com/v5/challenges/7028a2fb-694b-4d4b-bac6-8def4ee3fc9b

Currently Migrated Possible Values are:
- digitalRunPoints
- submissionLimit
- allowStockArt
- submissionsViewable
- environment
- codeRepo
- filetypes
- isBanner

**Comment by sushilshinde** [comment]
```
environment
codeRepo
```

Not showing

**Comment by rootelement** [comment]
I'm still working through migration, but this is confirmed fixed in the latest version:
http://api.topcoder-dev.com/v5/challenges?legacyId=30051802
http://api.topcoder-dev.com/v4/challenges/30051802

Note - I'm re-migrating challenges, so UUIDs may have changed.
