### ISSUE TITLE
Challenge Manager Prize Money Save Issues

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#198]
https://github.com/topcoder-platform/challenge-engine-ui/issues/694
https://github.com/topcoder-platform/challenge-engine-ui/issues/689

@rootelement @ThomasKranitsas I think we have a small problem in legacy challenge creation/update process. It might be causing the https://github.com/topcoder-platform/challenge-engine-ui/issues/694 as well. What I found from my debugging today is as follows:
• CM sends PUT request to v5 challenge api with correct prizeSets (@thomaskranitsas we do pass default prizeSet with 0 money but here I am assuming that user has filled the correct prize money before hitting Save as Draft button), when user hits Save as Draft button.
• v5 API updates the data and raises challenge update event to the bus
• legacy processor consumes this event, and observes that challenge does not have legacyId set yet so, it internally calls its logic for handling the challenge create event. https://github.com/topcoder-platform/legacy-challenge-processor/blob/c6d9f607aef47af7088d2ec6e05aad8ec9e38de2/src/services/ProcessorService.js#L283
• now legacy processor creates the legacy challenge and PATCHES the challenge via v5 challenge api https://github.com/topcoder-platform/legacy-challenge-processor/blob/c6d9f607aef47af7088d2ec6e05aad8ec9e38de2/src/services/ProcessorService.js#L219
Let me know if that is not the process right now. Now, the problem is that I am seeing logs in challenge api two times (because we are hitting that two times) and first time when it was hit by CM, it has the correct prize money but when it was hit second time by legacy processor, it does not have correct prize money. Prize money is set to 0 in second case (logs at 17:43:04 in attached screenshot have prizeSets defaulted to 0 while logs at 17:42:59 has the correct prizeSet)

<img width="1221" alt="Screen Shot 2020-06-19 at 6 18 09 PM" src="https://user-images.githubusercontent.com/2417632/86018540-22f0c100-ba43-11ea-80b5-f5a2cdb52e3c.png">

**Comment by ThomasKranitsas** [comment]
I see that a default value for the `prizeSets` is passed with a prize of `0`. The thing is that the Challenge API posts the whole challenge object on the BUS API (Kafka) instead of only the modified properties as the data is required on the legacy processor and this causes the issue of `prizeSets` being reset even after you change the values.

I confirmed the issue is because of the default prizeSets. I created `http://api.topcoder-dev.com/v5/challenges/f4fd88de-34e6-4272-89fc-a26410dc86e0` within POSTMAN without any prizeSets and it worked perfectly fine and nothing was reset.

@vikasrohit please remove the default prizes on challenge creation.

cc @rootelement

**Comment by vikasrohit** [comment]
ok, I get it and I would remove default prizeSet for now but I am still thinking about the root cause. IMO, the problem seems to be event ordering. I want to make sure that if in future we are setting something else instead of prizeSet for New project which is not avoidable to send, would the cause of the current problem will override it as well?

fyi @rootelement

**Comment by vikasrohit** [comment]
@ThomasKranitsas @rootelement  I think we need to identify the root cause and fix it as soon as possible because it seems it creating more issues then only reseting the prize money. I tried to create a challenge on production and once I saved it to draft status and done couple of changes via Direct/OR, the challenge in v5 api seems to be reset with many fields e.g.
- review type is reset to internal
- public specification is set to HTML version of the content
- tags are removed
- copilot fee is set to zero
- legacyId is now set as string instead of a number etc.

<img width="1080" alt="Screen Shot 2020-07-15 at 7 15 24 PM" src="https://user-images.githubusercontent.com/2417632/87552669-9d6e4180-c6cf-11ea-831e-671e2fecefd6.png">

**Comment by vikasrohit** [comment]
Updating the issue with latest conversations via Slack.
After recent changes via commit https://github.com/topcoder-platform/legacy-challenge-migration-script/commit/0e578def4e329cf991a967a9923a03c88bd2ddfc, it seems the issue is not happening (at least frequently). We still need to keep an eye on it to ensure that it is not happening even for intermittent cases.

**Comment by rootelement** [comment]
Can we close this now @vikasrohit ?
