### ISSUE TITLE
Timezone of the registration date is incorrect V5, when user has registered from V4.

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/challenge-api#231]
Timezone of the registration date is incorrect V5, when user has registered from V4.

<img width="1440" alt="Screenshot 2020-07-21 at 8 52 53 PM" src="https://user-images.githubusercontent.com/58783823/88073822-43202580-cb94-11ea-8d70-5129cef656d2.png">

**Comment by ThomasKranitsas** [comment]
This could be because of the sync delay. There are many ways this could happen. To name a few:
- There is a delay until the processor picks up the event and creates the record on V5
- The challenge was not yet migrated to V5 so the processor keeps reposting the event until the challenge gets available and then be able to create the record

@rootelement If that's really an issue, I guess we can read the date from the legacy object and reuse the same otherwise we can simply ignore this issue.
