### ISSUE TITLE
Non task challenge is also not returned with task challenge

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/challenge-api#276]
@rootelement I think we don't yet support listing tasks (which are not assigned to the user) for a non admin user, however, I think the current logic is causing non task challenges to to missing from the response as well for non admin users. We have user `pshah_manager` who is not able to see tasks and challenge which were created using the same account. This user is not an admin but it did create few challenges some of which are tasks (few assigned to other users and few unassigned).

**Comment by vikasrohit** [comment]
@rootelement @ThomasKranitsas suggested a fix https://github.com/topcoder-platform/challenge-api/pull/277. I tried the query in postman by directly calling the ES endpoint but not tested the code itself. Further, I am not sure if it creates issue with any other use case e.g. public challenge listings or not.

**Comment by rootelement** [comment]
@vikasrohit I've merged the PR to dev. Please test there. If it looks good to you, we can have the QA team test as well.

**Comment by ThomasKranitsas** [comment]
@rootelement I think I found the issue.

If you check this https://api.topcoder-dev.com/v5/challenges/b91e4c01-ec46-404f-8691-aa631776d0e5

It has:

```
task: {
   isTask: true
},
```

Note that the `isAssigned` and `memberId` properties are missing and since the query is trying to match with `{ match_phrase: { 'task.isAssigned': false } }`, it fails.
If that's actually the reason, we can simply fix it by adding default values to those fields (`false` and `null` respectively)

**Comment by rootelement** [comment]
@ThomasKranitsas is it better to add default values, or check for false OR non-existent?

**Comment by ThomasKranitsas** [comment]
I'd say better to add default values.. No need to over-complicate the query as that could have a performance impact

**Comment by ThomasKranitsas** [comment]
@rootelement should I fix this?

**Comment by rootelement** [comment]
Fixed in https://github.com/topcoder-platform/challenge-api/pull/292
