### ISSUE TITLE
Track field not matching Swagger or working with POST / PATCH

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/challenge-api#96]
@ThomasKranitsas  - When we create the base challenge on the `Launch New` page, we send these details:

### Sample POST

```
{
    "status": "New",
    "projectId": "6583",
    "name": "Justin Test 4"
}
```

### Problem

The problem is:

* The `track` isn't sent properly at create time because it hasn't been selected.
* The `track` property can't be PATCH'd after the fact - it returns a 400 error from the challenge API
* The `track` can't be sent as part of the initial POST because it's failing:
```
{
    "message": "\"track\" is not allowed"
}
```

The Swagger YAML for the challenge API does list the `track` field, but I can't seem to add it properly.

![Screen_Shot_2020-05-01_at_16_19_24](https://user-images.githubusercontent.com/21790/80786748-e5e58b00-8bc7-11ea-974e-487e7f2e0cc4.png)

**Comment by rootelement** [comment]
Track has been moved under the legacy object. The swagger is out of date.
```
"legacy": {
        "track": "DEVELOP",
        "confidentialityType": "public",
        "reviewType": "INTERNAL"
    },
```
But all the other things you mention are valid. Also, when the `New` status was added, the createChallenge and update function JOIs were not updated, so even if the function doesn't require it, the JOI does. So that's why these are failing. This needs to be updated.
